config/routes.rb
Ninegates::Application.routes.draw do
  resources :players

  resources :hands

  resources :games

  root 'dummy#index'
end

app/models/game.rb
class Game < ActiveRecord::Base
	include Bitfields

	has_many :players
	has_many :hands

	#bitfield :rule_flags, game_flag_hash

	def game_flag_hash
		# TODO: get some sleep and implement this
		# something something load game_rules.yaml
		flags = Hash.new
		flags[1] = "TODO"

		flags
	end
end

app/models/hand.rb
class Hand < ActiveRecord::Base
	include Bitfields

	belongs_to :game

	#bitfield :p1_yaku, yaku_bitfield_hash
	#bitfield :p2_yaku, yaku_bitfield_hash
	#bitfield :p3_yaku, yaku_bitfield_hash
	#bitfield :p4_yaku, yaku_bitfield_hash

	def yaku_bitfield_hash
		# TODO: get some sleep and implement this 
		# something something load yaku.yaml
		yaku = Hash.new
		yaku[1] = "Riichi"

		yaku
	end
end

app/models/player.rb
class Player < ActiveRecord::Base
	belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dummy_controller.rb
class DummyController < ApplicationController
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:date, :name, :rule_flags, :p1_id, :p2_id, :p3_id, :p4_id, :p1_final_score, :p2_final_score, :p3_final_score, :p4_final_score)
    end
end

app/controllers/hands_controller.rb
class HandsController < ApplicationController
  before_action :set_hand, only: [:show, :edit, :update, :destroy]

  # GET /hands
  # GET /hands.json
  def index
    @hands = Hand.all
  end

  # GET /hands/1
  # GET /hands/1.json
  def show
  end

  # GET /hands/new
  def new
    @hand = Hand.new
  end

  # GET /hands/1/edit
  def edit
  end

  # POST /hands
  # POST /hands.json
  def create
    @hand = Hand.new(hand_params)

    respond_to do |format|
      if @hand.save
        format.html { redirect_to @hand, notice: 'Hand was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hand }
      else
        format.html { render action: 'new' }
        format.json { render json: @hand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hands/1
  # PATCH/PUT /hands/1.json
  def update
    respond_to do |format|
      if @hand.update(hand_params)
        format.html { redirect_to @hand, notice: 'Hand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hands/1
  # DELETE /hands/1.json
  def destroy
    @hand.destroy
    respond_to do |format|
      format.html { redirect_to hands_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hand
      @hand = Hand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hand_params
      params.require(:hand).permit(:round_name, :p1_change, :p1_yaku, :p1_is_yakuman, :p2_change, :p2_yaku, :p2_is_yakuman, :p3_change, :p3_yaku, :p3_is_yakuman, :p4_change, :p4_yaku, :p4_is_yakuman, :dora)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player }
      else
        format.html { render action: 'new' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dummy_helper.rb
module DummyHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/hands_helper.rb
module HandsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rule_flags %><br>
    <%= f.text_field :rule_flags %>
  </div>
  <div class="field">
    <%= f.label :p1_id %><br>
    <%= f.number_field :p1_id %>
  </div>
  <div class="field">
    <%= f.label :p2_id %><br>
    <%= f.number_field :p2_id %>
  </div>
  <div class="field">
    <%= f.label :p3_id %><br>
    <%= f.number_field :p3_id %>
  </div>
  <div class="field">
    <%= f.label :p4_id %><br>
    <%= f.number_field :p4_id %>
  </div>
  <div class="field">
    <%= f.label :p1_final_score %><br>
    <%= f.number_field :p1_final_score %>
  </div>
  <div class="field">
    <%= f.label :p2_final_score %><br>
    <%= f.number_field :p2_final_score %>
  </div>
  <div class="field">
    <%= f.label :p3_final_score %><br>
    <%= f.number_field :p3_final_score %>
  </div>
  <div class="field">
    <%= f.label :p4_final_score %><br>
    <%= f.number_field :p4_final_score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Name</th>
      <th>Rule flags</th>
      <th>P1</th>
      <th>P2</th>
      <th>P3</th>
      <th>P4</th>
      <th>P1 final score</th>
      <th>P2 final score</th>
      <th>P3 final score</th>
      <th>P4 final score</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.date %></td>
        <td><%= game.name %></td>
        <td><%= game.rule_flags %></td>
        <td><%= game.p1_id %></td>
        <td><%= game.p2_id %></td>
        <td><%= game.p3_id %></td>
        <td><%= game.p4_id %></td>
        <td><%= game.p1_final_score %></td>
        <td><%= game.p2_final_score %></td>
        <td><%= game.p3_final_score %></td>
        <td><%= game.p4_final_score %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @game.date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Rule flags:</strong>
  <%= @game.rule_flags %>
</p>

<p>
  <strong>P1:</strong>
  <%= @game.p1_id %>
</p>

<p>
  <strong>P2:</strong>
  <%= @game.p2_id %>
</p>

<p>
  <strong>P3:</strong>
  <%= @game.p3_id %>
</p>

<p>
  <strong>P4:</strong>
  <%= @game.p4_id %>
</p>

<p>
  <strong>P1 final score:</strong>
  <%= @game.p1_final_score %>
</p>

<p>
  <strong>P2 final score:</strong>
  <%= @game.p2_final_score %>
</p>

<p>
  <strong>P3 final score:</strong>
  <%= @game.p3_final_score %>
</p>

<p>
  <strong>P4 final score:</strong>
  <%= @game.p4_final_score %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/hands/_form.html.erb
<%= form_for(@hand) do |f| %>
  <% if @hand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hand.errors.count, "error") %> prohibited this hand from being saved:</h2>

      <ul>
      <% @hand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :round_name %><br>
    <%= f.text_field :round_name %>
  </div>
  <div class="field">
    <%= f.label :p1_change %><br>
    <%= f.number_field :p1_change %>
  </div>
  <div class="field">
    <%= f.label :p1_yaku %><br>
    <%= f.text_field :p1_yaku %>
  </div>
  <div class="field">
    <%= f.label :p1_is_yakuman %><br>
    <%= f.check_box :p1_is_yakuman %>
  </div>
  <div class="field">
    <%= f.label :p2_change %><br>
    <%= f.number_field :p2_change %>
  </div>
  <div class="field">
    <%= f.label :p2_yaku %><br>
    <%= f.text_field :p2_yaku %>
  </div>
  <div class="field">
    <%= f.label :p2_is_yakuman %><br>
    <%= f.check_box :p2_is_yakuman %>
  </div>
  <div class="field">
    <%= f.label :p3_change %><br>
    <%= f.number_field :p3_change %>
  </div>
  <div class="field">
    <%= f.label :p3_yaku %><br>
    <%= f.text_field :p3_yaku %>
  </div>
  <div class="field">
    <%= f.label :p3_is_yakuman %><br>
    <%= f.check_box :p3_is_yakuman %>
  </div>
  <div class="field">
    <%= f.label :p4_change %><br>
    <%= f.number_field :p4_change %>
  </div>
  <div class="field">
    <%= f.label :p4_yaku %><br>
    <%= f.text_field :p4_yaku %>
  </div>
  <div class="field">
    <%= f.label :p4_is_yakuman %><br>
    <%= f.check_box :p4_is_yakuman %>
  </div>
  <div class="field">
    <%= f.label :dora %><br>
    <%= f.text_field :dora %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hands/edit.html.erb
<h1>Editing hand</h1>

<%= render 'form' %>

<%= link_to 'Show', @hand %> |
<%= link_to 'Back', hands_path %>

app/views/hands/index.html.erb
<h1>Listing hands</h1>

<table>
  <thead>
    <tr>
      <th>Round name</th>
      <th>P1 change</th>
      <th>P1 yaku</th>
      <th>P1 is yakuman</th>
      <th>P2 change</th>
      <th>P2 yaku</th>
      <th>P2 is yakuman</th>
      <th>P3 change</th>
      <th>P3 yaku</th>
      <th>P3 is yakuman</th>
      <th>P4 change</th>
      <th>P4 yaku</th>
      <th>P4 is yakuman</th>
      <th>Dora</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @hands.each do |hand| %>
      <tr>
        <td><%= hand.round_name %></td>
        <td><%= hand.p1_change %></td>
        <td><%= hand.p1_yaku %></td>
        <td><%= hand.p1_is_yakuman %></td>
        <td><%= hand.p2_change %></td>
        <td><%= hand.p2_yaku %></td>
        <td><%= hand.p2_is_yakuman %></td>
        <td><%= hand.p3_change %></td>
        <td><%= hand.p3_yaku %></td>
        <td><%= hand.p3_is_yakuman %></td>
        <td><%= hand.p4_change %></td>
        <td><%= hand.p4_yaku %></td>
        <td><%= hand.p4_is_yakuman %></td>
        <td><%= hand.dora %></td>
        <td><%= link_to 'Show', hand %></td>
        <td><%= link_to 'Edit', edit_hand_path(hand) %></td>
        <td><%= link_to 'Destroy', hand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hand', new_hand_path %>

app/views/hands/new.html.erb
<h1>New hand</h1>

<%= render 'form' %>

<%= link_to 'Back', hands_path %>

app/views/hands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Round name:</strong>
  <%= @hand.round_name %>
</p>

<p>
  <strong>P1 change:</strong>
  <%= @hand.p1_change %>
</p>

<p>
  <strong>P1 yaku:</strong>
  <%= @hand.p1_yaku %>
</p>

<p>
  <strong>P1 is yakuman:</strong>
  <%= @hand.p1_is_yakuman %>
</p>

<p>
  <strong>P2 change:</strong>
  <%= @hand.p2_change %>
</p>

<p>
  <strong>P2 yaku:</strong>
  <%= @hand.p2_yaku %>
</p>

<p>
  <strong>P2 is yakuman:</strong>
  <%= @hand.p2_is_yakuman %>
</p>

<p>
  <strong>P3 change:</strong>
  <%= @hand.p3_change %>
</p>

<p>
  <strong>P3 yaku:</strong>
  <%= @hand.p3_yaku %>
</p>

<p>
  <strong>P3 is yakuman:</strong>
  <%= @hand.p3_is_yakuman %>
</p>

<p>
  <strong>P4 change:</strong>
  <%= @hand.p4_change %>
</p>

<p>
  <strong>P4 yaku:</strong>
  <%= @hand.p4_yaku %>
</p>

<p>
  <strong>P4 is yakuman:</strong>
  <%= @hand.p4_is_yakuman %>
</p>

<p>
  <strong>Dora:</strong>
  <%= @hand.dora %>
</p>

<%= link_to 'Edit', edit_hand_path(@hand) %> |
<%= link_to 'Back', hands_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninegates</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>